version: "3.8"
services:
  kafka:
    image: confluentinc/cp-kafka:7.0.1
    restart: always
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CREATE_TOPICS: 'create-cs:1:1' # topic:partition:replicas
      KAFKA_ZOOKEEPER_CONNECT: 'cp_zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - kafka-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - cp_zookeeper

  cp_zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: cp_zookeeper
    restart: always
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-net

networks:
  kafka-net:
    name: ec-network
    driver: bridge
    external: true
